
import type { Department, Doctor, Testimonial } from './types';
import { Building2, HeartPulse, Brain, Bone, Baby } from 'lucide-react';

export const placeholderDepartments: Department[] = [
  {
    id: 'cardiology',
    name: 'Cardiology',
    description: 'Comprehensive heart care, from prevention to advanced treatment.',
    icon: HeartPulse,
    imageUrl: 'https://images.unsplash.com/photo-1708433061324-06cfe6d48762?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxM3x8Y2FyZGlvbG9neSUyMHxlbnwwfHx8fDE3NDg4NDMxNTV8MA&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    id: 'neurology',
    name: 'Neurology',
    description: 'Expert diagnosis and treatment for brain, spine, and nervous system disorders.',
    icon: Brain,
    imageUrl: 'https://images.unsplash.com/photo-1711409645921-ef3db0501f96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxuZXVyb2xvZ3klMjB8ZW58MHx8fHwxNzQ4ODQzMzA0fDA&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    id: 'orthopedics',
    name: 'Orthopedics',
    description: 'Specialized care for bones, joints, muscles, ligaments, and tendons.',
    icon: Bone,
    imageUrl: 'https://images.unsplash.com/photo-1582380330092-636f9aff6aaf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxvcnRob3BlZGljfGVufDB8fHx8MTc0ODg0MzQzOHww&ixlib=rb-4.1.0&q=80&w=1080',
  },
  {
    id: 'pediatrics',
    name: 'Pediatrics',
    description: 'Dedicated healthcare for infants, children, and adolescents.',
    icon: Baby,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'children doctor'
  },
  {
    id: 'general',
    name: 'General Medicine',
    description: 'Primary care services for all ages, focusing on overall health and wellness.',
    icon: Building2,
    imageUrl: 'https://placehold.co/600x400.png',
    'data-ai-hint': 'family doctor'
  },
];

export const placeholderDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Emily Carter',
    specialty: 'Cardiologist',
    departmentId: 'cardiology',
    departmentName: 'Cardiology',
    bio: 'Dr. Carter is a board-certified cardiologist with over 15 years of experience in treating complex heart conditions. She is passionate about preventive care and patient education.',
    availability: 'Mon, Wed, Fri: 9 AM - 5 PM',
    imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxmZW1hbGUlMjBkb2N0b3J8ZW58MHx8fHwxNzQ4ODQzNzA5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    qualifications: ['MD', 'FACC (Fellow of the American College of Cardiology)'],
    experienceYears: 15,
    'data-ai-hint': 'doctor portrait professional',
  },
  {
    id: '2',
    name: 'Dr. Benjamin Lee',
    specialty: 'Neurologist',
    departmentId: 'neurology',
    departmentName: 'Neurology',
    bio: 'Dr. Lee specializes in diagnosing and treating neurological disorders, including stroke, epilepsy, and multiple sclerosis. He is known for his compassionate approach.',
    availability: 'Tue, Thu: 10 AM - 6 PM',
    imageUrl: 'https://placehold.co/300x300.png',
    'data-ai-hint': 'male doctor',
    qualifications: ['MD', 'PhD (Neuroscience)'],
    experienceYears: 12,
  },
  {
    id: '3',
    name: 'Dr. Sarah Green',
    specialty: 'Orthopedic Surgeon',
    departmentId: 'orthopedics',
    departmentName: 'Orthopedics',
    bio: 'Dr. Green is a renowned orthopedic surgeon specializing in sports injuries and joint replacement. She uses the latest minimally invasive techniques.',
    availability: 'Mon, Tue, Thu: 8 AM - 4 PM',
    imageUrl: 'https://images.unsplash.com/photo-1607990283143-e81e7a2c9349?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxmZW1hbGUlMjBkb2N0b3J8ZW58MHx8fHwxNzQ4ODQzNzA5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    'data-ai-hint': 'doctor portrait professional',
    qualifications: ['MD', 'FACS (Fellow of the American College of Surgeons)'],
    experienceYears: 18,
  },
  {
    id: '4',
    name: 'Dr. David Miller',
    specialty: 'Pediatrician',
    departmentId: 'pediatrics',
    departmentName: 'Pediatrics',
    bio: 'Dr. Miller provides comprehensive care for children from birth through adolescence. He believes in a family-centered approach to pediatric medicine.',
    availability: 'Mon - Fri: 9 AM - 5 PM',
    imageUrl: 'https://placehold.co/300x300.png',
    'data-ai-hint': 'pediatrician male',
    qualifications: ['MD', 'FAAP (Fellow of the American Academy of Pediatrics)'],
    experienceYears: 20,
  },
   {
    id: '5',
    name: 'Dr. Olivia White',
    specialty: 'General Practitioner',
    departmentId: 'general',
    departmentName: 'General Medicine',
    bio: 'Dr. White offers primary care services to patients of all ages. She emphasizes preventive health and wellness, building long-term relationships with her patients.',
    availability: 'Mon, Wed, Fri: 8 AM - 4 PM; Tue: 10 AM - 6 PM',
    imageUrl: 'https://images.unsplash.com/photo-1603030431751-f3109cd8d53b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOHx8ZmVtYWxlJTIwZG9jdG9yfGVufDB8fHx8MTc0ODg0MzcwOXww&ixlib=rb-4.1.0&q=80&w=1080',
    'data-ai-hint': 'doctor portrait',
    qualifications: ['MD', 'Board Certified in Family Medicine'],
    experienceYears: 10,
  },
  {
    id: '6',
    name: 'Dr. James Brown',
    specialty: 'Cardiologist',
    departmentId: 'cardiology',
    departmentName: 'Cardiology',
    bio: 'Dr. Brown is a highly skilled cardiologist focusing on interventional cardiology and heart rhythm disorders. He is committed to providing cutting-edge care.',
    availability: 'Tue, Thu, Fri: 9 AM - 3 PM',
    imageUrl: 'https://placehold.co/300x300.png',
    'data-ai-hint': 'male cardiologist',
    qualifications: ['MD', 'FSCAI (Fellow of the Society for Cardiovascular Angiography and Interventions)'],
    experienceYears: 14,
  },
];

export const placeholderTestimonials: Testimonial[] = [
  {
    id: '1',
    patientName: 'John Doe',
    quote: "The care I received at MediLink was exceptional. Dr. Carter and her team were professional and compassionate. I highly recommend this hospital.",
    imageUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'male patient',
    date: '2024-03-15',
  },
  {
    id: '2',
    patientName: 'Jane Smith',
    quote: "My experience with Dr. Lee for my neurological condition was life-changing. The facilities are top-notch, and the staff is incredibly supportive.",
    imageUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'female patient',
    date: '2024-04-22',
  },
  {
    id: '3',
    patientName: 'Michael B.',
    quote: "Dr. Green performed my knee surgery, and I'm back to my active lifestyle sooner than I expected. The entire orthopedic department is fantastic.",
    imageUrl: 'https://placehold.co/100x100.png',
    'data-ai-hint': 'male patient',
    date: '2024-05-10',
  },
];

